//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewKMA.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NewKMA.Resources.ImageResources", typeof(ImageResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string transfer_confamount {
            get {
                return ResourceManager.GetString("transfer_confamount", resourceCulture);
            }
        }
        
        internal static string transfer_ConfNote {
            get {
                return ResourceManager.GetString("transfer_ConfNote", resourceCulture);
            }
        }
        
        internal static string transfer_confdate {
            get {
                return ResourceManager.GetString("transfer_confdate", resourceCulture);
            }
        }
        
        internal static string transfer_confrefno {
            get {
                return ResourceManager.GetString("transfer_confrefno", resourceCulture);
            }
        }
        
        internal static string dueDate {
            get {
                return ResourceManager.GetString("dueDate", resourceCulture);
            }
        }
        
        internal static string transfer_confref {
            get {
                return ResourceManager.GetString("transfer_confref", resourceCulture);
            }
        }
        
        internal static string transfer_ConfSchedule {
            get {
                return ResourceManager.GetString("transfer_ConfSchedule", resourceCulture);
            }
        }
        
        internal static string confirmmobileatatm {
            get {
                return ResourceManager.GetString("confirmmobileatatm", resourceCulture);
            }
        }
    }
}
